FEATURES = [
    "Live packet capture",
    "Rootless synthetic demo mode",
    "PCAP replay mode",
    "Destination IP filtering",
    "Source IP filtering",
    "Destination port filtering",
    "Multiple destination ports",
    "Destination port ranges",
    "Protocol filtering",
    "Interface selection",
    "Runtime filter changes",
    "Runtime port changes",
    "Runtime top-N changes",
    "Pause and resume",
    "Remote-free local controller",
    "Unix socket command channel",
    "JSON controller responses",
    "Graceful shutdown",
    "Session reset",
    "Snapshot export",
    "CSV top talker export",
    "JSONL event export",
    "Offline-only geo lookup",
    "Nettop location.csv geo database",
    "Pure stdlib geo resolver",
    "CIDR geo range support",
    "Start/end geo range support",
    "Automatic location.csv discovery",
    "Private IP classification",
    "Loopback classification",
    "Link-local classification",
    "Multicast classification",
    "Reserved IP classification",
    "Geo result LRU cache",
    "Country ranking",
    "Unique IP count",
    "Per-IP packet count",
    "Per-IP byte count",
    "Per-IP current PPS",
    "Per-IP 10-second PPS",
    "Per-IP 60-second PPS",
    "Per-IP low PPS",
    "Per-IP peak PPS",
    "Per-IP first timestamp",
    "Per-IP last timestamp in ns",
    "Per-IP source ports",
    "Per-IP destination ports",
    "Per-IP protocol counts",
    "Per-IP MAC association",
    "Per-IP TCP flag counts",
    "Global current PPS",
    "Global average PPS",
    "Global byte rate",
    "Total packet counter",
    "Total byte counter",
    "Filtered packet counter",
    "Protocol breakdown",
    "Destination port ranking",
    "Source port ranking",
    "Destination IP ranking",
    "TCP flag breakdown",
    "Packet size buckets",
    "Recent event ring buffer",
    "MAC packet counts",
    "MAC current PPS",
    "MAC 60-second PPS",
    "New source IP alerts",
    "New MAC alerts",
    "High PPS alerts",
    "Configurable high PPS threshold",
    "Responsive terminal dashboard",
    "Narrow terminal fallback",
    "Wide terminal multi-panel layout",
    "Service name hints for common ports",
    "Scapy high-fidelity capture",
    "Raw socket fallback",
    "No online APIs",
    "No telemetry",
    "No cloud dependency",
    "No third-party geo dependency",
    "Linux-first runtime layout",
    "Systemd service template",
    "Debian packaging metadata",
    "APT repository instructions",
    "Python package entry point",
    "Single modern nettop CLI",
    "Doctor command",
    "Feature list command",
    "Version command",
    "Human-readable status",
    "Machine-readable status",
    "Scripting-friendly CLI",
    "Bounded in-memory events",
    "Low allocation hot path",
    "Thread-safe counters",
    "Configurable refresh interval",
    "Configurable event buffer size",
    "Root privilege guidance",
    "Optional Rich UI",
    "Optional Scapy dependency",
    "Works with bundled location.csv",
    "Works with custom location.csv files",
    "Works without Scapy in fallback mode",
    "Local-only controller permissions",
    "Controller socket cleanup",
    "Country flag display where supported",
    "ASN display-ready resolver",
    "Organization display-ready resolver",
    "Demo traffic includes private and public IPs",
    "Demo traffic includes MACs",
    "Demo traffic includes TCP/UDP/ICMP",
    "Timestamps use nanoseconds",
    "JSON snapshots include raw metrics",
    "CSV exports are spreadsheet-ready",
    "Systemd environment override path",
    "Debian dependency recommendations",
    "Build script for source archives",
    "Project README",
    "Linux install guide",
    "Apt publishing guide",
    "Security notes",
    "Performance notes",
    "Extensible module layout",
    "Capture module boundary",
    "Store module boundary",
    "Geo module boundary",
    "Control module boundary",
    "TUI module boundary",
    "Exporter module boundary",
    "Alert module boundary",
    "Typed dataclass models",
    "Simple unit-testable helpers",
]


def feature_text() -> str:
    lines = ["Nettop feature catalog", ""]
    for idx, item in enumerate(FEATURES, 1):
        lines.append(f"{idx:03d}. {item}")
    return "\n".join(lines)
