name: Build Debian Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            debhelper \
            dh-python \
            python3-all \
            python3-setuptools \
            python3-rich \
            python3-scapy \
            pybuild-plugin-pyproject \
            python3-build

      - name: Copy Debian packaging
        run: |
          cp -r packaging/debian ./debian

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc

      - name: Find package
        run: |
          mkdir artifacts
          cp ../*.deb artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.deb
          generate_release_notes: true